### ISSUE TITLE
Update the JWTAuthProvider  

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/scigateway#1423]
## Description

Introduce the `OGJWTAuthProvider` class to streamline handling of admin users in the OG. This class will provide the `isAdmin` method to verify if a user has administrative privileges based on the `authorised_routes` in their JWT.

## Tasks

- [ ] Implement the `OGJWTAuthProvider` class, inheriting from `JWTAuthProvider`, and add the `isAdmin` method.
  - Ensure `isAdmin` checks the token's `authorised_routes` for the presence of `'/users GET'`.
- [ ] Write unit tests for the `isAdmin` method to cover:
  - No token in `localStorage`.
  - Token with no or empty `authorised_routes`.
  - Token containing the `'/users GET'` route.

## Acceptance Criteria

- [ ] `OGJWTAuthProvider` correctly identifies admin status through `isAdmin`.
- [ ] Unit tests validate all possible scenarios for `isAdmin`.

**Comment by louise-davies** [comment]
Now that we changed how the backend works, we won't need a specific OGJWTAuthProvider. Instead the existing JWTAuthProvider should:

- Add the maintenance route functionality similar to the ICAT auth provider
- Fix that it doesn't store the user's admin status when the user logs in
